cachecloud-open-web/src/main/java/com/sohu/cache/entity/AppDesc.java
package com.sohu.cache.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;

import com.alibaba.fastjson.JSONObject;
import com.sohu.cache.constant.AppDescEnum;
import com.sohu.cache.constant.AppDescEnum.AppImportantLevel;
import com.sohu.cache.constant.AppStatusEnum;
import com.sohu.cache.util.ConstUtils;

/**
 * 应用的信息，包括分片、类型以及各分片的ip
 * <p/>
 * User: lingguo
 * Date: 14-5-29
 * Time: 下午9:42
 */
public class AppDesc implements Serializable {
    private static final long serialVersionUID = -3507970915810652761L;

    /**
     * 应用id
     */
    private long appId;
    
    /**
     * 应用秘钥
     */
    private String appKey;

    /**
     * 应用名称
     */
    private String name;

    /**
     * 用户id
     */
    private long userId;

    /**
     * 应用状态, 0未分配，1是申请了未审批，2是审批并发布, 3应用下线
     */
    private int status;

    /**
     * 应用描述
     */
    private String intro;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 申请通过的时间
     */
    private Date passedTime;

    /**
     * 类型
     */
    private int type;

    /**
     * 类型描述
     */
    private String typeDesc;

    /**
     * 负责人
     */
    private String officer;

    /**
     * 版本号
     */
    private int verId;

    /**
     * 是否测试：1是0否
     */
    private int isTest;

    /**
     * 是否有后端数据源: 1是0否
     */
    private int hasBackStore;

    /**
     * 是否需要持久化: 1是0否
     */
    private int needPersistence;

    /**
     * 预估qps
     */
    private int forecaseQps;

    /**
     * 是否需要热备: 1是0否
     */
    private int needHotBackUp;

    /**
     * 预估条目数
     */
    private int forecastObjNum;

    /**
     * 内存报警阀值
     */
    private int memAlertValue;
    
    /**
     * 客户端连接数报警阀值
     */
    private int clientConnAlertValue;
    
    /**
     * 客户端机器机房
     */
    private String clientMachineRoom;
    
    /**
     * redis密码
     */
    private String password;
    
    /**
     * 重要度，默认重要
     */
    private int importantLevel = AppImportantLevel.IMPORTANT.getValue();

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getPassedTime() {
        return passedTime;
    }

    public void setPassedTime(Date passedTime) {
        this.passedTime = passedTime;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getOfficer() {
        return officer;
    }

    public void setOfficer(String officer) {
        this.officer = officer;
    }

    public int getVerId() {
        return verId;
    }

    public void setVerId(int verId) {
        this.verId = verId;
    }

    public int getIsTest() {
        return isTest;
    }

    public void setIsTest(int isTest) {
        this.isTest = isTest;
    }

    public int getHasBackStore() {
        return hasBackStore;
    }

    public void setHasBackStore(int hasBackStore) {
        this.hasBackStore = hasBackStore;
    }

    public int getNeedPersistence() {
        return needPersistence;
    }

    public void setNeedPersistence(int needPersistence) {
        this.needPersistence = needPersistence;
    }


    public int getForecaseQps() {
        return forecaseQps;
    }

    public void setForecaseQps(int forecaseQps) {
        this.forecaseQps = forecaseQps;
    }

    public int getNeedHotBackUp() {
        return needHotBackUp;
    }

    public void setNeedHotBackUp(int needHotBackUp) {
        this.needHotBackUp = needHotBackUp;
    }

    public int getForecastObjNum() {
        return forecastObjNum;
    }

    public void setForecastObjNum(int forecastObjNum) {
        this.forecastObjNum = forecastObjNum;
    }

    public int getMemAlertValue() {
        return memAlertValue;
    }

    public void setMemAlertValue(int memAlertValue) {
        this.memAlertValue = memAlertValue;
    }

    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    public String getClientMachineRoom() {
        return clientMachineRoom;
    }

    public void setClientMachineRoom(String clientMachineRoom) {
        this.clientMachineRoom = clientMachineRoom;
    }
    
    public String getAppKey() {
        return appKey;
    }

    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    public int getClientConnAlertValue() {
        return clientConnAlertValue;
    }

    public void setClientConnAlertValue(int clientConnAlertValue) {
        this.clientConnAlertValue = clientConnAlertValue;
    }
    
    public int getImportantLevel() {
        return importantLevel;
    }

    public void setImportantLevel(int importantLevel) {
        this.importantLevel = importantLevel;
    }
    
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 应用运行天数
     */
    public int getAppRunDays() {
        if (createTime == null) {
            return -1;
        }
        Date now = new Date();
        long diff = now.getTime() - createTime.getTime();
        return (int) (diff / TimeUnit.DAYS.toMillis(1));
    }

    public String getTypeDesc() {
        if (type <= 0) {
            return "";
        } else if (type == ConstUtils.CACHE_TYPE_REDIS_CLUSTER) {
            return "redis-cluster";
        } else if (type == ConstUtils.CACHE_REDIS_SENTINEL) {
            return "redis-sentinel";
        } else if (type == ConstUtils.CACHE_REDIS_STANDALONE) {
            return "redis-standalone";
        }
        return "";
    }
    
    public String getCreateTimeFormat(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if(createTime != null){
            return sdf.format(createTime);
        }
        return "";
    }


    @Override
    public String toString() {
        return JSONObject.toJSONString(this);
    }

    public String getStatusDesc() {
        AppStatusEnum appStatusEnum = AppStatusEnum.getByStatus(status);
        if (appStatusEnum != null) {
            return appStatusEnum.getInfo();
        }
        return "";
    }


    /**
     * 是否下线
     * @return
     */
    public boolean isOffline() {
        return status == AppStatusEnum.STATUS_OFFLINE.getStatus();
    }

    /**
     * 是否是测试
     * @return
     */
    public boolean isTest() {
        return isTest == AppDescEnum.AppTest.IS_TEST.getValue();
    }

    /**
     * 非常重要
     * @return
     */
    public boolean isVeryImportant() {
        return importantLevel == AppDescEnum.AppImportantLevel.VERY_IMPORTANT.getValue();
    }
    
    /**
     * 超级重要
     * @return
     */
    public boolean isSuperImportant() {
        return importantLevel == AppDescEnum.AppImportantLevel.SUPER_IMPORTANT.getValue();
    }

}

cachecloud-open-web/src/main/java/com/sohu/cache/entity/AppStats.java
package com.sohu.cache.entity;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.math.NumberUtils;

/**
 * Created by yijunzhang on 14-6-9.
 */
public class AppStats {

    /**
     * 应用id
     */
    private long appId;

    /**
     * 收集时间:格式yyyyMMddHHmm/yyyyMMdd/yyyyMMddHH
     */
    private long collectTime;

    /**
     * 命中数量
     */
    private long hits;

    /**
     * 未命中数量
     */
    private long misses;

    /**
     * 命令执行次数
     */
    private long commandCount;

    /**
     * 内存占用
     */
    private long usedMemory;

    /**
     * 过期key数量
     */
    private long expiredKeys;

    /**
     * 驱逐key数量
     */
    private long evictedKeys;

    /**
     * 网络输入字节
     */
    private long netInputByte;

    /**
     * 网络输出字节
     */
    private long netOutputByte;

    /**
     * 客户端连接数
     */
    private int connectedClients;

    /**
     * 存储对象数
     */
    private long objectSize;

    /**
     * 累加的实例数
     */
    private int accumulation;

    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 命令统计集合
     */
    private List<AppCommandStats> commandStatsList;

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public long getCollectTime() {
        return collectTime;
    }

    public void setCollectTime(long collectTime) {
        this.collectTime = collectTime;
    }

    public long getHits() {
        return hits;
    }
    
    /**
     * 命中率
     * @return
     */
    public long getHitPercent() {
        long total = hits + misses;
        if (total == 0) {
            return 0;
        } else {
            NumberFormat formatter = new DecimalFormat("0");
            return NumberUtils.toLong(formatter.format(hits * 100.0 / total));
        }
    }
    
    public void setHits(long hits) {
        this.hits = hits;
    }

    public long getMisses() {
        return misses;
    }

    public void setMisses(long misses) {
        this.misses = misses;
    }

    public long getUsedMemory() {
        return usedMemory;
    }

    public void setUsedMemory(long usedMemory) {
        this.usedMemory = usedMemory;
    }

    public long getExpiredKeys() {
        return expiredKeys;
    }

    public void setExpiredKeys(long expiredKeys) {
        this.expiredKeys = expiredKeys;
    }

    public long getEvictedKeys() {
        return evictedKeys;
    }

    public void setEvictedKeys(long evictedKeys) {
        this.evictedKeys = evictedKeys;
    }

    public int getConnectedClients() {
        return connectedClients;
    }

    public void setConnectedClients(int connectedClients) {
        this.connectedClients = connectedClients;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "AppStats{" +
                "appId=" + appId +
                ", collectTime=" + collectTime +
                ", hits=" + hits +
                ", misses=" + misses +
                ", usedMemory=" + usedMemory +
                ", expiredKeys=" + expiredKeys +
                ", evictedKeys=" + evictedKeys +
                ", connectedClients=" + connectedClients +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                ", objectSize=" + objectSize +
                ", accumulation=" + accumulation +
                '}';
    }

    public long getCommandCount() {
        return commandCount;
    }

    public void setCommandCount(long commandCount) {
        this.commandCount = commandCount;
    }

    public void setObjectSize(long objectSize) {
        this.objectSize = objectSize;
    }

    public long getObjectSize() {
        return objectSize;
    }

    public int getAccumulation() {
        return accumulation;
    }

    public void setAccumulation(int accumulation) {
        this.accumulation = accumulation;
    }

    public List<AppCommandStats> getCommandStatsList() {
        return commandStatsList;
    }

    public void setCommandStatsList(List<AppCommandStats> commandStatsList) {
        this.commandStatsList = commandStatsList;
    }

    public long getNetInputByte() {
        return netInputByte;
    }

    public void setNetInputByte(long netInputByte) {
        this.netInputByte = netInputByte;
    }

    public long getNetOutputByte() {
        return netOutputByte;
    }

    public void setNetOutputByte(long netOutputByte) {
        this.netOutputByte = netOutputByte;
    }
}

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appCommand.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="row">
    <div id="console" class="console"></div>
    <script type="text/javascript">
        $(document).ready(function () {
            var console = $('#console');
            var controller = console.console({
                promptLabel: 'appId:${appId}> ',
                commandValidate: function (line) {
                    if (line == "") return false;
                    else return true;
                },
                commandHandle: function (line,report) {
                    $.ajax({
                        url: "/admin/app/commandExecute.json",
                        data: {appId: $('#appId').val(), command: line},
                        dataType: "json",
                        success: function (result) {
                            report([
                                {msg: result.result,
                                    className: "jquery-console-message-value"}
                            ]);
                        }
                    });
                },
                autofocus: true,
                animateScroll: true,
                promptHistory: true
            });
        });
    </script>
    <center><h4><font color='red'>注意：非测试应用只可以执行只读命令，如有需要清理数据请联系管理员！</font></h4></center>

    <input type="hidden" id="appId" value="${appId}">

</div>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appCommandAnalysis.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<script type="text/javascript">
var firstCommand = '${firstCommand}';
var startDate = '${startDate}';
var endDate = '${endDate}';
var yesterDate = '${yesterDay}';
var betweenOneDay = '${betweenOneDay}';
var appId = '${appId}'; 
var chartParams = "&startDate="+startDate+"&endDate="+endDate;
var chartParamsCompare = "&startDate="+yesterDate+"&endDate="+startDate;
var betweenParams = "&startDate="+yesterDate+"&endDate="+endDate;
Highcharts.setOptions({
	global : {
		useUTC : false
	}
});
Highcharts.setOptions({
	colors : ['#2f7ed8', '#E3170D', '#0d233a', '#8bbc21', '#1aadce',
			'#492970', '#804000', '#f28f43', '#77a1e5',
			'#c42525', '#a6c96a']
});

function changeCommandChart(value){
	document.getElementById("firstCommand").value = value;
	document.getElementById("formSingCommand").submit();
}
</script>

<div class="container">
	<br/>
	<form method="post" action="/admin/app/index.do" id="formSingCommand">
		<div class="row">
			<div style="float:right">
					<label style="font-weight:bold;text-align:left;">
					 	开始日期:&nbsp;&nbsp;
					</label>
					<input type="text" size="21" name="startDate" id="startDate" value="${startDate}" onFocus="WdatePicker({startDate:'%y-%M-01',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})"/>
					<label style="font-weight:bold;text-align:left;">
					 	结束日期:
					</label>
					<input type="text" size="20" name="endDate" id="endDate" value="${endDate}" onFocus="WdatePicker({startDate:'%y-%M-01',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})"/>
					<input type="hidden" name="appId" value="${appDetail.appDesc.appId}">
					<input type="hidden" name="tabTag" value="app_command_analysis">
					<input type="hidden" id="firstCommand" name="firstCommand" value="${firstCommand}">
					<label>&nbsp;<input type="submit" class="btn-4" value="查询"/></label>
			</div>
		</div>
		<div class="row">
				<c:set var="needSelect" value="0"></c:set>
				&nbsp;&nbsp;Top5命令:
				<c:forEach items="${allCommands}" var="item" varStatus="stat">
					<c:choose>
						<c:when test="${stat.index < 5}">
								<input type="radio" name="optionsRadios" value="${item.commandName}" 
								<c:if test="${firstCommand == item.commandName}">checked="checked"</c:if>
								 onchange="changeCommandChart(this.value)" />
								${item.commandName}
						</c:when>
						<c:otherwise>
							<c:set var="needSelect" value="1"></c:set>
						</c:otherwise>
					</c:choose>
				</c:forEach>
				<c:if test="${needSelect == 1}">
					&nbsp;&nbsp;&nbsp;其余命令:
					<select name="optionsRadios" onchange="changeCommandChart(this.value)">
						<option>请选择</option>
						<c:forEach items="${allCommands}" var="item" varStatus="stat">
							<c:choose>
								<c:when test="${stat.index >= 5}">
									<label>
										<option value="${item.commandName}" <c:if test="${firstCommand == item.commandName}">selected</c:if>>
							         		${item.commandName}
							        	</option>
									</label>							
								</c:when>
							</c:choose>
						</c:forEach>
					</select>
				</c:if>
				
		</div>
	</form>
	<script type="text/javascript">
		var title = "<b>"+firstCommand+"命令</b>";
		if(betweenOneDay == 1){
			$(document).ready(
				function() {
					var options = getOption("containerSingleCommand", "<b>全命令统计</b>", "次数");
					var commandsUrl = "/admin/app/getMutiDatesCommandStats.json?appId=" + appId + "&commandName=" + firstCommand + betweenParams;
					$.ajax({
						type : "get",
						url : commandsUrl,
						async : true,
						success : function(data) {
							var dates = new Array();
							dates.push(startDate); 
							dates.push(yesterDate);
							pushOptionSeries(options, data, dates, "命令趋势图");
							new Highcharts.Chart(options);
						}
					});
			 });
		}else{
			$(document).ready(
				function() {
					var options = getOption("containerSingleCommand", title, "次数");
					var commandsUrl = "/admin/app/getCommandStats.do?appId=" + appId + "&commandName=" + firstCommand + chartParams;
					$.ajax({
						type : "get",
						url : commandsUrl,
						async : false,
						success : function(data) {
							var nameLegend = firstCommand + "命令趋势图";
							var finalPoints = getSeriesPoints(data, nameLegend);
							options.series.push(finalPoints);
						}
					});
					new Highcharts.Chart(options);
			 });
		}
	</script>
	
	
	<div id="containerSingleCommand"
		style="min-width: 310px; height: 350px; margin: 0 auto"></div>

</div>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appDaily.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<div class="container">

	<br/>
    <form method="get" action="/admin/app/index.do">
		<div class="row">
			<div style="float:right">
				<label style="font-weight:bold;text-align:left;">
				 	&nbsp;日期:&nbsp;&nbsp;
				</label>
				<input type="text" size="21" name="dailyDate" id="dailyDate" value="${dailyDate}" onFocus="WdatePicker({startDate:'%y-%M-01',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})"/>
				
				<input type="hidden" name="appId" value="${appDesc.appId}">
				<input type="hidden" name="tabTag" value="app_daily">
				<label>&nbsp;<input type="submit" class="btn-4" value="查询"/></label>
			</div>
		</div>
	</form>


    <div class="row">
        <div class="page-header">
            <h4>客户端相关</h4> 
        </div>
        <table class="table table-striped table-hover">
            <tbody>
             <tr>
                 <td>客户端值分布(全天)</td>
                 <td>${appDailyData.valueSizeDistributeCountDescHtml}</td>
                 <td>客户端异常个数(全天)</td>
                 <td>${appDailyData.clientExceptionCount}</td>
                 <td>客户端连接数(每分钟)</td>
                 <td>
                  最大值:${appDailyData.maxMinuteClientCount} <br/>
                     平均值:${appDailyData.avgMinuteClientCount}
                 </td>
             </tr>
            </tbody>
        </table>
    </div>
    
    <div class="row">
        <div class="page-header">
            <h4>服务端相关</h4> 
        </div>
        <table class="table table-striped table-hover">
            <tbody>
	             <tr>
	                 <td>慢查询个数(全天)</td>
	                 <td>${appDailyData.slowLogCount}</td>
	                 <td>命令次数(每分钟)</td>
	                 <td>
	                 	最大值:${appDailyData.maxMinuteCommandCount} <br/>
	                    平均值:${appDailyData.avgMinuteCommandCount}
	                 </td>
	                 <td>命中率(每分钟)</td>
	                 <td>
	                  	最大值:${appDailyData.maxMinuteHitRatio}% <br/>
	                    最小值:${appDailyData.minMinuteHitRatio}% <br/>
	                    平均值:${appDailyData.avgHitRatio}%
	                 </td>
	             </tr>
	             
	             <tr>
	                 <td>内存使用量(全天)</td>
	                 <td>
	                 	平均使用量:${appDailyData.avgUsedMemory} M<br/>
                        最大使用量:${appDailyData.maxUsedMemory} M
	                 </td>
	                 <td>过期键数(全天)</td>
	                 <td>
	                 	${appDailyData.expiredKeysCount}
	                 </td>
	                 <td>剔除键数(全天)</td>
	                 <td>
	                  	${appDailyData.evictedKeysCount}
	                 </td>
	             </tr>
	             
	             
	             <tr>
	                 <td>键个数(全天)</td>
	                 <td>
	                 	平均值:${appDailyData.avgObjectSize}<br/>
                        最大值:${appDailyData.maxObjectSize}
	                 </td>
	                 <td>input流量(每分钟)</td>
	                 <td>
	                 	平均值:${appDailyData.avgMinuteNetInputByte} M<br/>
                       	 最大值:${appDailyData.maxMinuteNetInputByte} M
	                 </td>
	                 <td>output流量(每分钟)</td>
	                 <td>
	                  	 平均:${appDailyData.avgMinuteNetOutputByte} M<br/>
                       	 最大:${appDailyData.maxMinuteNetOutputByte} M<br/>
	                 </td>
	             </tr>
	             
            </tbody>
        </table>
    </div>
    
    
    <br/><br/><br/>
</div>




cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appDemo.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp" %>
<div class="row">
    <br/>
    
    Maven Dependency：
    <div id="dependency" class="highlight">
        <pre class="prettyprint">
            <c:forEach var="line" items="${dependency}">
            ${line}<br/>
            </c:forEach>
        </pre>
    </div>

	Demo Code：
    <div id="code" class="highlight">
        <pre class="prettyprint">
        <c:forEach var="line" items="${code}">
            ${line}<br/>
        </c:forEach>
        </pre>
    </div>
    
    Rest API：
    <div id="code" class="highlight">
        <pre class="prettyprint">
            ${restApi}<br/>
        </pre>
    </div>
    
    <c:if test="${springConfig != null}">
    	Spring Config Demo：
	    <div id="springConfig" class="highlight">
	        <pre class="prettyprint">
	        <c:forEach var="line" items="${springConfig}">
	            ${line}<br/>
	        </c:forEach>
	        </pre>
	    </div>
    </c:if>
    
</div>
<script>
    prettyPrint();
</script>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appTopology.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<div class="row">
    <div class="page-header">
        <h4>应用拓扑结构-<a href="/admin/app/index.do?appId=${appDesc.appId}">${appDesc.name}</a></h4>
    </div>
    <div style="margin-top: 20px">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <td>ID</td>
                <td>实例</td>
                <td>实例状态</td>
                <td>内存使用</td>
                <td>对象数</td>
                <td>连接数</td>
                <td>命中率</td>
                <td>碎片率</td>
                <td>角色</td>
                <td>主实例ID</td>
            </tr>
            </thead>
            <tbody>
            <c:forEach var="instance" items="${instanceList}" varStatus="status">
            	<c:set var="instanceStatsMapKey" value="${instance.ip}:${instance.port}"></c:set>
                <tr>
                    <td>
                    	 <a href="/admin/instance/index.do?instanceId=${instance.id}" target="_blank">${instance.id}</a>
                    	 <c:if test="${instance.masterInstanceId == 0 && instance.status != 2}">
							<span class="glyphicon glyphicon-star"></span>	                         
	                     </c:if>
                    </td>
                    <td><a href="/server/index.do?ip=${instance.ip}" target="_blank">${instance.ip}</a>:${instance.port}</td>
                    <td>${instance.statusDesc}</td>
					<td>
						<c:choose>
							<c:when test="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent >= 80}">
								<c:set var="progressBarStatus" value="progress-bar-danger"/>
							</c:when>
							<c:otherwise>
								<c:set var="progressBarStatus" value="progress-bar-success"/>
							</c:otherwise>
						</c:choose>
					
                         <div class="progress margin-custom-bottom0">
                               <div class="progress-bar ${progressBarStatus}"
                                    role="progressbar"
                                    aria-valuenow="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}"
                                    aria-valuemax="100"
                                    aria-valuemin="0"
                                    style="width: ${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}%">
                                    
	                               	<label style="color: #000000">
	                                   <fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).usedMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Used/<fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).maxMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Total
	                               	</label>
                                </div>
                         </div>
                  </td>
                  <td>
                  ${(instanceStatsMap[instanceStatsMapKey]).currItems}
                  </td>
                  <td>${(instanceStatsMap[instanceStatsMapKey]).currConnections}</td>
                  <td>${(instanceStatsMap[instanceStatsMapKey]).hitPercent}</td>
                  <td>
	                  <c:set var="memFragmentationRatio" value="${(instanceStatsMap[instanceStatsMapKey]).memFragmentationRatio}"/>
	                  <c:choose>
	                		<c:when test="${memFragmentationRatio > 5 && (instanceStatsMap[instanceStatsMapKey]).usedMemory > 1024 * 1024 * 100}">
	                			  <c:set var="memFragmentationRatioLabel" value="label-danger"/>
	                		</c:when>
	                		<c:when test="${memFragmentationRatio >= 3 && memFragmentationRatio < 5 && (instanceStatsMap[instanceStatsMapKey]).usedMemory > 1024 * 1024 * 100}">
	                			  <c:set var="memFragmentationRatioLabel" value="label-warning"/>
	                		</c:when>
	                		<c:otherwise>
	                			  <c:set var="memFragmentationRatioLabel" value="label-success"/>
	                 		</c:otherwise>
	                  </c:choose>
	                  <label class="label ${memFragmentationRatioLabel}">${memFragmentationRatio}</label>
                  </td>
                  <td>${instance.roleDesc}</td>
                  <c:choose>
                     <c:when test="${instance.masterInstanceId >0}">
                         <td>
                             <a href="/admin/instance/index.do?instanceId=${instance.masterInstanceId}" target="_blank">${instance.masterInstanceId}</a>
                         </td>
                     </c:when>
                     <c:otherwise>
                         <td></td>
                     </c:otherwise>
                 </c:choose>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>